### ISSUE TITLE
【bug反馈】可能是pcdel指令执行逻辑导致的

### ISSUE THREAD

**Issue by ChunChong777** [sealdice/sealdice-android#12]
绑定角色卡时，pc del留空默认用玩家名检索角色，如果成功检索到未绑定的角色卡，会：
◆删除对应角色
◆清除群内空白卡
◆解除当前群绑定状态，启用群内空白卡
◇原先绑定角色会变为★（绑定信息有当前群，但当前群却不是绑定状态）
——————————————
出现◇的情况后，如果再去绑定另外一张角色卡。
会出现[错误★显示的角色卡]无法用pc untagall解绑，同时也无法用pc del删除的情况。
——————————————
【复现步骤】
1.准备三张未绑定的角色卡
2.pc tag绑定第一张
3.nn 更名为第二张
4.发送[pc del]
5.pc tag绑定第三张

此时第一张会变成[错误显示★的角色卡]，无法用pc untagall解绑，也无法用pc del删除

**Comment by Szzrain** [comment]
这是安卓版代码仓库，关于核心的bug反馈请在 [这里](https://github.com/sealdice/sealdice-plan/issues/new/choose) 进行
