### ISSUE TITLE
[Bug]:手机骰 $tHour  显示现时间错误

### ISSUE THREAD

**Issue by Samukawa19** [sealdice/sealdice-android#20]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看master branch或最新测试版的更新内容，并未提及该 bug 已被修复的情况
- [X] 已有issue中并没有看见其他人与我反馈相同的问题

### 问题描述

手机骰 $tHour  显示现时间显示到其他时区了，咨询群友后得知pc骰无误，但是手机骰显示时间比现时间晚8小时。

### 如何复现

.text {%$tHour%}
（测试时间：15:00，UTC+8:00）

### 你期望发生的

15

### 实际上发生的

7

### 日志文件

![0C430F3FC8C0F9231CE02E73B2E74B40](https://user-images.githubusercontent.com/118671756/236794472-a3b20d1a-abe0-45eb-8c12-2fb8f052d3dd.jpg)

### App版本

v0.4.9-rc

### 海豹核心版本

1.2.6 v20230410

### 设备信息

华为nova 7 5G

### 帐号类型

QQ

**Comment by Szzrain** [comment]
golang/go#20455
